// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVHFtNI74dyRaUzfebWptp4VfQrhow5ZY',
    appId: '1:113214106564:web:d44c5ea60c934f2ef6d291',
    messagingSenderId: '113214106564',
    projectId: 'notificacoes-firebase-3c4a7',
    authDomain: 'notificacoes-firebase-3c4a7.firebaseapp.com',
    storageBucket: 'notificacoes-firebase-3c4a7.appspot.com',
    measurementId: 'G-YC0C3XLR1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMNwc26F9nHR0QIja8l6X6uctaKC3Zuyk',
    appId: '1:113214106564:android:50b69ee9f605efd5f6d291',
    messagingSenderId: '113214106564',
    projectId: 'notificacoes-firebase-3c4a7',
    storageBucket: 'notificacoes-firebase-3c4a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxzR9uqU0hljRj35q8EdLPVjjYHJKs8X8',
    appId: '1:113214106564:ios:e6c29d83ce033f2ef6d291',
    messagingSenderId: '113214106564',
    projectId: 'notificacoes-firebase-3c4a7',
    storageBucket: 'notificacoes-firebase-3c4a7.appspot.com',
    iosClientId: '113214106564-1gsodtl3ls5qq591bbp9hr0bme8p1ovs.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxzR9uqU0hljRj35q8EdLPVjjYHJKs8X8',
    appId: '1:113214106564:ios:e6c29d83ce033f2ef6d291',
    messagingSenderId: '113214106564',
    projectId: 'notificacoes-firebase-3c4a7',
    storageBucket: 'notificacoes-firebase-3c4a7.appspot.com',
    iosClientId: '113214106564-1gsodtl3ls5qq591bbp9hr0bme8p1ovs.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );
}
